export { GeneralSettingsSection } from './settings-section-general'
export { SpeechToTextSettingsSection } from './settings-section-speech-to-text'
export { AgentsSettingsSection } from './settings-section-agents'
export { ClawSettingsSection } from './settings-section-claw'
export { KeyboardShortcutsSettingsSection } from './settings-section-shortcuts'
export { RemoteResourcesSettingsSection } from './settings-section-remote-resources'
